project:
  type: website
  resources: Assets
  output-dir: docs

website:
  title: "Brooke Benton"
  navbar:
    background: "#14234B"
    left:
      - href: index.qmd
        text: Home
      - Projects.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/brooke-benton-7143b624a/
      - icon: lightbulb
        href: Assets/Brooke Benton Resume .pdf

format:
  html:
    theme: 
      light: flatly
      dark: darkly 
        #- custom.scss
    css: styles.css
    toc: true



